// Generated from libavfilter/opencl/convolution.cl
const char *ff_opencl_source_convolution =
"#line 1 \"libavfilter/opencl/convolution.cl\"\n"
"/*\n"
" * This file is part of FFmpeg.\n"
" *\n"
" * FFmpeg is free software; you can redistribute it and/or\n"
" * modify it under the terms of the GNU Lesser General Public\n"
" * License as published by the Free Software Foundation; either\n"
" * version 2.1 of the License, or (at your option) any later version.\n"
" *\n"
" * FFmpeg is distributed in the hope that it will be useful,\n"
" * but WITHOUT ANY WARRANTY; without even the implied warranty of\n"
" * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU\n"
" * Lesser General Public License for more details.\n"
" *\n"
" * You should have received a copy of the GNU Lesser General Public\n"
" * License along with FFmpeg; if not, write to the Free Software\n"
" * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA\n"
" */\n"
"\n"
"__kernel void convolution_global(__write_only image2d_t dst, __read_only  image2d_t src)\n"
"{\n"
"    const sampler_t sampler = (CLK_NORMALIZED_COORDS_FALSE | CLK_FILTER_NEAREST);\n"
"    const int BLOCKSIZE = 8;\n"
"    const int factor = 1;\n"
"    const int MATRIXSIZE = 3;\n"
"    const int HALFMATRIXSZ = (MATRIXSIZE / 2);\n"
"    const float matrix[9] = {1, 1, 1, 1, -7, 1, 1, 1, 1};\n"
"\n"
"    const int X = get_global_id(0);\n"
"    const int Y = get_global_id(1);\n"
"\n"
"    const int BLOCK_X = X * BLOCKSIZE;\n"
"    const int BLOCK_Y = Y * BLOCKSIZE;\n"
"\n"
"    int2 loc    = (int2)(X, Y);\n"
"    float4 convPix = (float4)(0.0f, 0.0f, 0.0f, 0.0f);\n"
"    for (int conv_i = -HALFMATRIXSZ; conv_i <= HALFMATRIXSZ; conv_i++) {\n"
"        for (int conv_j = -HALFMATRIXSZ; conv_j <= HALFMATRIXSZ; conv_j++) {\n"
"            float4 px = read_imagef(src, sampler, loc + (int2)(conv_j, conv_i));\n"
"            convPix += px * matrix[(conv_i+1)*MATRIXSIZE+(conv_j+1)];\n"
"        }\n"
"     }\n"
"     write_imagef(dst, loc, convPix / factor);\n"
"}\n"
"__kernel void convolution_local(__write_only image2d_t dst,\n"
"                            __read_only  image2d_t src)\n"
"{\n"
"    const sampler_t sampler = (CLK_NORMALIZED_COORDS_FALSE |\n"
"                               CLK_ADDRESS_CLAMP_TO_EDGE |\n"
"                               CLK_FILTER_NEAREST);\n"
"\n"
"    const int factor = 1;\n"
"    const int MATRIXSIZE = 3;\n"
"    const float matrix[9] = {1, 1, 1, 1, -7, 1, 1, 1, 1};\n"
"\n"
"\n"
"    const int WS = 8;\n"
"\n"
"    const int X = get_group_id(0);\n"
"    const int Y = get_group_id(1);\n"
"\n"
"    const int BLOCK_X = X * WS;\n"
"    const int BLOCK_Y = Y * WS;\n"
"\n"
"    const int f  =  get_local_id(0);\n"
"    const int f1 =  get_local_id(1);\n"
"\n"
"    const int HALFMATRIXSZ = (MATRIXSIZE / 2);\n"
"\n"
"\n"
"    __local float4 B[8*3*8*3];\n"
"\n"
"    for (int i = -1; i <= 1; i++) {\n"
"            for (int j = -1; j <= 1; j++) {\n"
"                    B[((i+1)*WS+f) * (WS*3) +(j+1)*WS+f1] = read_imagef(src, sampler, (int2)(BLOCK_X+f1 + (j*WS), BLOCK_Y+f + (i*WS)));\n"
"            }\n"
"    }\n"
"    barrier(CLK_LOCAL_MEM_FENCE);\n"
"\n"
"    float4 convPix = (float4)(0.0f, 0.0f, 0.0f, 0.0f);\n"
"    for (int conv_i = -HALFMATRIXSZ; conv_i <= HALFMATRIXSZ; conv_i++) {\n"
"                    for (int conv_j = -HALFMATRIXSZ; conv_j <= HALFMATRIXSZ; conv_j++) {\n"
"                            float4 px = B[(f+conv_i+WS) * (WS*3) + f1+conv_j+WS];\n"
"                            convPix += px * matrix[(conv_i+1)*MATRIXSIZE+(conv_j+1)];\n"
"                    }\n"
"            }\n"
"    barrier(CLK_LOCAL_MEM_FENCE);\n"
"    write_imagef(dst, (int2)(BLOCK_X+f1, BLOCK_Y+f), convPix / factor);\n"
"\n"
"}\n"
;
